### ISSUE TITLE
Private node in HECO

### ISSUE THREAD

**Issue by Neoblock8** [stars-labs/heco-chain#63]
Running private node in heco chain. Using same genesis file mentioned in heco document [https://docs.hecochain.com/#/dev/private_chain?id=using-docker-compose-to-deploy-a-private-chain]. In that, we modified set system contract code and extra data, the mining process is running successfully. But sending a transaction is always reverting and the mining process is stopped.

**Comment by darkegn** [comment]
I have the same problem, try to get gas Price:0 when sending a transaction. then it succeeds. but if you set gasPrice it crashes.

**Comment by darkegn** [comment]
> Running private node in heco chain. Using same genesis file mentioned in heco document [https://docs.hecochain.com/#/dev/private_chain?id=using-docker-compose-to-deploy-a-private-chain]. In that, we modified set system contract code and extra data, the mining process is running successfully. But sending a transaction is always reverting and the mining process is stopped.
> 
> **Logs:** INFO [12-25|12:50:13.914] Looking for peers peercount=0 tried=131 static=0 ERROR[12-25|12:50:15.002] ExecuteMsg failed **err="execution reverted" ret= panic: execution reverted** goroutine 88 [running]: github.com/ethereum/go-ethereum/consensus/congress.(*Congress).FinalizeAndAssemble(0xc00026b790, 0x19f9738, 0xc0003e3000, 0xc0023ad200, 0xc000e44d00, 0xc0001149d8, 0x1, 0x1, 0xc0017dd2f0, 0x0, ...) github.com/ethereum/go-ethereum/consensus/congress/congress.go:727 +0xd86 github.com/ethereum/go-ethereum/miner.(*worker).commit(0xc000328000, 0xc0017dd2f0, 0x0, 0x2, 0x0, 0xc001c0ab01, 0xc069e2c1c023924d, 0x13cf16b14a, 0x244c020, 0x0, ...) github.com/ethereum/go-ethereum/miner/worker.go:1060 +0x1ef github.com/ethereum/go-ethereum/miner.(*worker).commitNewWork(0xc000328000, 0xc001c0ab58, 0x1, 0x61c71382) github.com/ethereum/go-ethereum/miner/worker.go:1048 +0x845 github.com/ethereum/go-ethereum/miner.(*worker).mainLoop(0xc000328000) github.com/ethereum/go-ethereum/miner/worker.go:474 +0x8a7 created by github.com/ethereum/go-ethereum/miner.newWorker github.com/ethereum/go-ethereum/miner/worker.go:241 +0x5d6

I have the same problem, try to get gas Price:0 when sending a transaction. then it succeeds. but if you set gasPrice it crashes.
